version: '3.4'
services:
  db:
    image: mysql
    env_file:
      - ./express-db/.env
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dbtest

networks:
  dbtest:
    driver: bridge

volumes:
  db_data: {}
